import Card from "../../scripts/models/card.js";
const baseImageUrl = "/cards/eastern-front/images/";
const backImage = baseImageUrl + "back.png";
const cards = [
  new Card(1, baseImageUrl + "1.png", backImage, "command-defense", "G11"),
  new Card(2, baseImageUrl + "2.png", backImage, "command-defense", "B03"),
  new Card(3, baseImageUrl + "3.png", backImage, "command-defense", "J17"),
  new Card(4, baseImageUrl + "4.png", backImage, "command-defense", "B08"),
  new Card(5, baseImageUrl + "5.png", backImage, "command-defense", "I06"),
  new Card(6, baseImageUrl + "6.png", backImage, "command-defense", "G15"),
  new Card(7, baseImageUrl + "7.png", backImage, "command-defense", "K12"),
  new Card(8, baseImageUrl + "8.png", backImage, "command-defense", "H03"),
  new Card(9, baseImageUrl + "9.png", backImage, "command-defense", "B15"),
  new Card(10, baseImageUrl + "10.png", backImage, "command-defense", "G10"),
  new Card(11, baseImageUrl + "11.png", backImage, "", "C04"),
  new Card(12, baseImageUrl + "12.png", backImage, "", "I14"),
  new Card(13, baseImageUrl + "13.png", backImage, "", "D10"),
  new Card(14, baseImageUrl + "14.png", backImage, "", "J03"),
  new Card(15, baseImageUrl + "15.png", backImage, "", "H17"),
  new Card(16, baseImageUrl + "16.png", backImage, "reshuffle", "I08"),
  new Card(17, baseImageUrl + "17.png", backImage, "", "F05"),
  new Card(18, baseImageUrl + "18.png", backImage, "", "D14"),
  new Card(19, baseImageUrl + "19.png", backImage, "", "E08"),
  new Card(20, baseImageUrl + "20.png", backImage, "reshuffle", "B05"),
  new Card(21, baseImageUrl + "21.png", backImage, "", "L15"),
  new Card(22, baseImageUrl + "22.png", backImage, "", "B10"),
  new Card(23, baseImageUrl + "23.png", backImage, "", "L03"),
  new Card(24, baseImageUrl + "24.png", backImage, "", "F17"),
  new Card(25, baseImageUrl + "25.png", backImage, "", "I10"),
  new Card(26, baseImageUrl + "26.png", backImage, "", "H05"),
  new Card(27, baseImageUrl + "27.png", backImage, "", "D17"),
  new Card(28, baseImageUrl + "28.png", backImage, "", "E12"),
  new Card(29, baseImageUrl + "29.png", backImage, "", "D03"),
  new Card(30, baseImageUrl + "30.png", backImage, "", "J15"),
  new Card(31, baseImageUrl + "31.png", backImage, "", "D08"),
  new Card(32, baseImageUrl + "32.png", backImage, "", "L05"),
  new Card(33, baseImageUrl + "33.png", backImage, "", "F15"),
  new Card(34, baseImageUrl + "34.png", backImage, "", "I12"),
  new Card(35, baseImageUrl + "35.png", backImage, "", "G07"),
  new Card(36, baseImageUrl + "36.png", backImage, "", "D15"),
  new Card(37, baseImageUrl + "37.png", backImage, "", "G08"),
  new Card(38, baseImageUrl + "38.png", backImage, "", "D05"),
  new Card(39, baseImageUrl + "39.png", backImage, "", "L17"),
  new Card(40, baseImageUrl + "40.png", backImage, "", "G12"),
  new Card(41, baseImageUrl + "41.png", backImage, "", "J05"),
  new Card(42, baseImageUrl + "42.png", backImage, "reshuffle", "H15"),
  new Card(43, baseImageUrl + "43.png", backImage, "", "C12"),
  new Card(44, baseImageUrl + "44.png", backImage, "", "F03"),
  new Card(45, baseImageUrl + "45.png", backImage, "", "B17"),
  new Card(46, baseImageUrl + "46.png", backImage, "command", "K08"),
  new Card(47, baseImageUrl + "47.png", backImage, "command", "C07"),
  new Card(48, baseImageUrl + "48.png", backImage, "command", "K13"),
  new Card(49, baseImageUrl + "49.png", backImage, "command", "F10"),
  new Card(50, baseImageUrl + "50.png", backImage, "command", "K07"),
  new Card(51, baseImageUrl + "51.png", backImage, "command", "E13"),
  new Card(52, baseImageUrl + "52.png", backImage, "command", "K10"),
  new Card(53, baseImageUrl + "53.png", backImage, "command", "G05"),
  new Card(54, baseImageUrl + "54.png", backImage, "command", "G17"),
  new Card(55, baseImageUrl + "55.png", backImage, "command", "B12"),
];
export default { cards };
